// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Seguridad.Infraestructura.Persistencia;

#nullable disable

namespace Seguridad.Infraestructura.Migrations
{
    [DbContext(typeof(ContextoBaseDeDatos))]
    [Migration("20260612162002_InicializacionSeguridad")]
    partial class InicializacionSeguridad
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Seguridad.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid?>("EntidadAsociadaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Activo = true,
                            PasswordHash = "$2a$12$LeuS9i3uiy9rsM6FItlleeXGtoz.AnzI3RpIXH4LjvE3o5.Elhway",
                            Rol = "Admision",
                            Username = "agustin.martinez"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Activo = true,
                            EntidadAsociadaId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            PasswordHash = "$2a$12$q5BgJzW8g89Un2g9aSinE.AuQSd8Q/81ZmcorHcp8AmNbSRrmeYby",
                            Rol = "Medico",
                            Username = "alejandro.salas"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Activo = true,
                            EntidadAsociadaId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            PasswordHash = "$2a$12$R.JYbHbqzf.2uTvKiSjxGOi6F94wKZsmgm589tTD3XuhgmBoQAVN.",
                            Rol = "Medico",
                            Username = "yonatan.rojas"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Activo = true,
                            EntidadAsociadaId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            PasswordHash = "$2a$12$BBupxtC1rfN.EXFsLthbKeN.LAxOH.LfTSo9LP6kLqr.BKsgMOrvm",
                            Rol = "Enfermera",
                            Username = "rodrigo.godoy"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Activo = true,
                            EntidadAsociadaId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            PasswordHash = "$2a$12$mgUlpwhxCUQIbOi/gR7mweJx8T1RaqdiCMJCT1iWHWpkXscL/zNY6",
                            Rol = "Enfermera",
                            Username = "matias.silva"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
